### ISSUE TITLE
N10 Capture Timeout

### ISSUE THREAD

**Issue by hexroytom** [crigroup/ensenso#11]
Hi, i got a timeout problem when using the package with N10 camera.
When i launch viewer.launch with my N10, the error came out as follows.

```
processGrabbing: NxLib error ExecutionFailed (17) occurred while accessing item Execute.

{
    "ErrorSymbol": "CaptureTimeout",
    "ErrorText": "Capture on camera 160824 failed with message: Waiting for images timed out.",
    "Execute": {
        "Command": "Capture",
        "Parameters": {
            "Cameras": null,
            "FinalTrigger": null,
            "InitialTrigger": null,
            "Operation": null,
            "Timeout": null,
            "WaitFor": null,
            "WaitForProjector": null
        }
    },
    "Time": 1007
}

```

I looked up in the Ensenso SDK manual for the error and it seems that the error resulted from an image pair not returned within a specified timeout. 
So, how can i change the timeout parameters or do i need to set other parameters to get the package work with N10?
BTW, i can use nxView or PCL 1.8 grabber to get N10 work, so i think the ensenso driver is intalled properly.
Looking forward to your reply, thanks.

**Comment by fsuarez6** [comment]
What [`TriggerMode`](https://github.com/crigroup/ensenso/blob/425eddcb0342233d401f36e21278a8249342c7de/launch/viewer.launch#L38) are you using?

**Comment by hexroytom** [comment]
I checked the launch file and RViz gui and the TriggerMode is Software.

**Comment by fsuarez6** [comment]
Strange. I can replicate your error changing the `TriggerMode` to `FallingEdge` or `RisingEdge`.
Without the N10 camera is very difficult for me to tell what the problem is.
The only difference I can think between this driver and the `PCL 1.8` grabber is the `openDevice` approach.
Here I [access the camera using its serial number](https://github.com/crigroup/ensenso/blob/425eddcb0342233d401f36e21278a8249342c7de/src/ensenso_grabber.cpp#L532) but [they do it using the camera id](https://github.com/PointCloudLibrary/pcl/blob/master/io/src/ensenso_grabber.cpp#L152)

You may want trying to change it back to use the camera id. You can see your camera id (cam ID) using `ueyecameramanager`

**Comment by hexroytom** [comment]
I changed the openDevice method using device ID, but new error came out as follows.

```
processGrabbing: NxLib error ExecutionFailed (17) occurred while accessing item Execute.

{
    "ErrorSymbol": "UEyeCamera",
    "ErrorText": "Capture on camera 160824 failed with message: Cannot wait for images when no capture running.",
    "Execute": {
        "Command": "Capture",
        "Parameters": {
            "Cameras": null,
            "FinalTrigger": null,
            "InitialTrigger": null,
            "Operation": null,
            "Timeout": null,
            "WaitFor": null,
            "WaitForProjector": null
        }
    },
    "Time": 22.58
```

Then i suddenly realized that  i forgot to git checkout to master branch.(I am using ROS Indigo.) 
Now i can get pointcloud and images with the master branch.
So sorry for my carelessness and thanks for your help.

**Comment by ruehr** [comment]
Having the same issue here, hexroytom I'm wodering what exactly you did checkout to master branch?

**Comment by hexroytom** [comment]
Hi, ruehr. I am using ROS Indigo and the readme says **master** branch is compatiable with Indigo, so i checkout to it.
